# Generated by Django 2.2.7 on 2019-11-26 18:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Escola',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200)),
                ('endereco', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='student.Endereco')),
            ],
        ),
        migrations.CreateModel(
            name='Aluno',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200)),
                ('nascimento', models.DateField()),
                ('serie', models.CharField(choices=[(1, 'primeiro ano'), (2, 'segundo ano'), (3, 'terceiro ano')], default=1, max_length=30)),
                ('email', models.EmailField(max_length=200)),
                ('senha', models.CharField(max_length=30)),
                ('endereco', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='student.Endereco')),
                ('escola', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='student.Escola')),
            ],
        ),
    ]
